package cz.xlisto.elektrodroid.dialogs;


import android.app.Dialog;
import android.os.Bundle;
import android.view.View;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.widget.SwitchCompat;
import androidx.fragment.app.DialogFragment;

import cz.xlisto.elektrodroid.R;
import cz.xlisto.elektrodroid.shp.ShPInvoice;


/**
 * Xlisto 02.04.2024 21:53
 */
public class SettingsInvoiceDialogFragment extends DialogFragment {
    public static final String TAG = "SettingsInvoiceDialogFragment";
    public static final String FLAG_RESULT_DIALOG_FRAGMENT = "flagResultSettingsInvoiceDialogFragment";
    public static final String RESULT = "result";
    private ShPInvoice shPInvoice;

    public static SettingsInvoiceDialogFragment newInstance() {
        return new SettingsInvoiceDialogFragment();
    }


    @NonNull
    @Override
    public Dialog onCreateDialog(@Nullable Bundle savedInstanceState) {
        shPInvoice = new ShPInvoice(requireContext());
        View view = View.inflate(requireContext(), R.layout.fragment_settings_invoice, null);
        SwitchCompat switchAutoGenerate = view.findViewById(R.id.switchSettingsInvoice);
        switchAutoGenerate.setChecked(shPInvoice.get(ShPInvoice.AUTO_GENERATE_INVOICE, true));

        TextView tvDescription = view.findViewById(R.id.tvAutogenerateSettingDescription);
        setDescription(switchAutoGenerate.isChecked(), tvDescription);

        AlertDialog.Builder builder = new AlertDialog.Builder(requireContext());
        builder.setTitle(getResources().getString(R.string.autogenerate_title));
        builder.setView(view);
        builder.setPositiveButton(getResources().getString(R.string.ok), (dialog, which) -> {
            Bundle bundle = new Bundle();
            bundle.putBoolean(RESULT, switchAutoGenerate.isChecked());
            getParentFragmentManager().setFragmentResult(SettingsInvoiceDialogFragment.FLAG_RESULT_DIALOG_FRAGMENT, bundle);
        });

        switchAutoGenerate.setOnCheckedChangeListener((buttonView, isChecked) -> {
            shPInvoice.set(ShPInvoice.AUTO_GENERATE_INVOICE, isChecked);
            setDescription(isChecked, tvDescription);
           });

        return builder.create();
    }


    /**
     * Nastaví popisek pod přepínačem
     * @param b true/false typ zobrazení popisku
     * @param tv TextView pro zobrazení popisku
     */
    private void setDescription(boolean b, TextView tv) {
        String autogenerateDescriptionNo = getResources().getString(R.string.autogenerate_no);
        String autogenerateDescriptionYes = getResources().getString(R.string.autogenerate_yes);
        if (b) {
            tv.setText(autogenerateDescriptionYes);
        } else {
            tv.setText(autogenerateDescriptionNo);
        }
    }
}
